Contents 
1. Importing libraries 
2. Importing data 
3. Checking and cleaning data

1. Importing libraries

In [2]:
import numpy as np 
import pandas as pd

2. Importing data

In [3]:
import_df = pd.read_excel('Raw_Data.xlsx',sheet_name='Main',header=[0])

#Transpose 
import_df = import_df.T

#Reset index 
import_df = import_df.reset_index()

#Set the first column to 'State'
import_df.columns = ['State']+list(import_df.iloc[0,1:])

#Drop the first row 
import_df = import_df.iloc[1:]

import_df.head()

,State,Total Population 2021,Population Growth or Decline 2010 to 2021,Households 2020,Labor Force (persons) Ann. Avg. 2021,Unemployment Rate Ann. Avg. 2021,Per Capita Personal Income 2021,Median Household Income 2020,Poverty Rate 2020,High School Diploma or More - Pct. of Adults 25+ 2020,...,Unemployment Rate 10-Year Pct. Chg,Educational Attainment in 2020,Total Population 25 and Older,Less than 9th Grade,"9th to 12th, No Diploma",High School Graduate (includes equiv.),"Some College, No Degree",Associate Degree,Bachelor's Degree,"Graduate, Professional or Doctorate Degree"
1,Alabama,5039877.0,0.054,1888504.0,NaN,NaN,49769.0,53958.0,14.9,0.869,...,NaN,NaN,3344006.0,133650.0,305297.0,1014342.0,721609.0,292064.0,546674.0,330370.0
2,Alaska,732673.0,0.032,255173.0,NaN,NaN,65813.0,79961.0,9.6,0.931,...,NaN,NaN,483436.0,11513.0,21663.0,137486.0,125645.0,42162.0,90161.0,54806.0
3,Arizona,7276316.0,0.138,2643430.0,NaN,NaN,55487.0,64652.0,12.8,0.879,...,NaN,NaN,4846056.0,248570.0,339349.0,1151988.0,1208298.0,429153.0,911228.0,557470.0
4,Arkansas,3025891.0,0.038,1170544.0,NaN,NaN,50625.0,51146.0,15.2,0.872,...,NaN,NaN,2026722.0,95403.0,164957.0,686812.0,445268.0,151587.0,308648.0,174047.0
5,California,39237836.0,0.053,13103114.0,NaN,NaN,76614.0,83001.0,11.5,0.839,...,NaN,NaN,26665143.0,2367996.0,1918542.0,5431385.0,5566520.0,2123827.0,5764827.0,3492046.0

2.1 Identify all the columns with NaN values and reconcile

In [5]:
nan_columns = import_df.isna().any()
nan_columns = nan_columns[nan_columns].index.tolist()

nan_columns

['Labor Force (persons) Ann. Avg. 2021',
 'Unemployment Rate Ann. Avg. 2021',
 'Population Over Time',
 'Population Estimates by Age in 2021',
 'Population Estimates by Race and Hispanic Origin in 2021',
 'Hispanic or Latino Population in 2021',
 'Households in 2020',
 'Housing Units in 2020',
 'Residential Building Permits in 2021',
 'Median Income',
 'Per Capita Personal Income (PCPI)',
 'Personal Income in 2021 ($000)',
 'Poverty Estimates',
 'Labor Force Annual Averages in Ann. Avg. 2021',
 'Total Labor Force',
 'Labor Force 5-Year Pct. Chg',
 'Labor Force 10-Year Pct. Chg',
 'Employed',
 'Employed 5-Year Pct. Chg',
 'Employed 10-Year Pct. Chg',
 'Unemployed',
 'Unemployed 5-Year Pct. Chg',
 'Unemployed 10-Year Pct. Chg',
 'Unemployment Rate',
 'Unemployment Rate 5-Year Pct. Chg',
 'Unemployment Rate 10-Year Pct. Chg',
 'Educational Attainment in 2020']

In [22]:
#Drop Population Over Time, 
#Population Estimates by Age in 2021


import_df['Population Estimates by Race and Hispanic Origin in 2021'].describe()

count       0
unique      0
top       NaN
freq      NaN
Name: Population Estimates by Race and Hispanic Origin in 2021, dtype: object

'Labor Force (persons) Ann. Avg. 2021',
 'Unemployment Rate Ann. Avg. 2021',
 'Population Over Time',
 'Population Estimates by Age in 2021',
 'Population Estimates by Race and Hispanic Origin in 2021',
 'Hispanic or Latino Population in 2021',
 'Households in 2020',
 'Housing Units in 2020',
 'Residential Building Permits in 2021',
 'Median Income',
 'Per Capita Personal Income (PCPI)',
 'Personal Income in 2021 ($000)',
 'Poverty Estimates',
 'Labor Force Annual Averages in Ann. Avg. 2021',
 'Total Labor Force',
 'Labor Force 5-Year Pct. Chg',
 'Labor Force 10-Year Pct. Chg',
 'Employed',
 'Employed 5-Year Pct. Chg',
 'Employed 10-Year Pct. Chg',
 'Unemployed',
 'Unemployed 5-Year Pct. Chg',
 'Unemployed 10-Year Pct. Chg',
 'Unemployment Rate',
 'Unemployment Rate 5-Year Pct. Chg',
 'Unemployment Rate 10-Year Pct. Chg',
 'Educational Attainment in 2020'